[project]
name = 'Tokenized-Service-Desk-Performance-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.optimization-implementation]
path = 'contracts/optimization-implementation.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-optimizer-verification]
path = 'contracts/performance-optimizer-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
